import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [initialValue, setInitialValue] = useState("");
  const [parsedValue, setParsedValue] = useState("");

  function handleInitialValue(e) {
    setInitialValue(initialTimestamps);
  }

  function parseText() {
    const initialTimestamps = initialValue;

    const timestampsSplittedByLineBreak = initialTimestamps.split(/\n/g);

    let result = "";

    timestampsSplittedByLineBreak.forEach((timestamp) => {
      const indexOfFirstSpace = timestamp.indexOf(" ");
      const slicedTimestamp = timestamp.slice(0, indexOfFirstSpace);
      const slicedRestOfText = timestamp.slice(indexOfFirstSpace);
      const timestampWithParenthesis = `(${slicedTimestamp})`;
      result += `${timestampWithParenthesis}${slicedRestOfText}\n`;
    });

    setParsedValue(result);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles["textareas-wrapper"]}>
          <textarea
            value={initialValue}
            onChange={(e) => setInitialValue(e.target.value)}
          />
          <button onClick={parseText}>parsear</button>
          <textarea value={parsedValue} />
        </div>
      </main>
    </>
  );
}
